version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: golang-web-api-hands-on
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/app
    command:
      - air
